package com.example.demo.Controller;

import com.example.demo.Brands.Brands;
import com.example.demo.CategoriesSports.CategoriesSports;
import com.example.demo.Services.ServicesCategoriesSports;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;


@org.springframework.stereotype.Controller
@RequestMapping(path = "/api/catsports/")
public class ControllerCategoriesSports {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ServicesCategoriesSports servicesCategoriesSports;

    @GetMapping("/all")
    public @ResponseBody Iterable<CategoriesSports> getAllCategoriesSports() {
        System.out.println(servicesCategoriesSports.categoriesSportsList());
        return servicesCategoriesSports.categoriesSportsList();
    }

    @GetMapping("/{id}")
    public @ResponseBody Optional<CategoriesSports> getOneCategoriesSports(@PathVariable Integer id) {
        System.out.println(servicesCategoriesSports.findById(id));
        return servicesCategoriesSports.findById(id);
    }
    // ADD
    @PostMapping(path = "/add") // NOK
    public @ResponseBody Optional<CategoriesSports> addNewCategoriesSports(@RequestParam String nameCategoriesSports) {
        CategoriesSports myCategoriesSports = servicesCategoriesSports.addNewCategoriesSports(nameCategoriesSports);
        System.out.println("DEBUG");
        System.out.println(myCategoriesSports);
        return Optional.ofNullable(myCategoriesSports);
    }

}
