package com.example.demo.Controller;

import com.example.demo.Brands.Brands;
import com.example.demo.Brands.BrandsRepository;
import com.example.demo.CategoriesSports.CategoriesSports;
import com.example.demo.CategoriesSports.CategoriesSportsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;


@org.springframework.stereotype.Controller
@RequestMapping(path = "/api/catsports/")
public class ControllerCategoriesSports {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CategoriesSportsRepository categoriesSportsRepository;

    @GetMapping("/all")
    public @ResponseBody Iterable<CategoriesSports> getAllCategoriesSports() {
        System.out.println(categoriesSportsRepository.findAll());
        return categoriesSportsRepository.findAll();
    }

}
